/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppEmergencyRouteImport } from './routes/_app/emergency'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppFunRouteImport } from './routes/_app/fun'
import { Route as AppFutureRouteImport } from './routes/_app/future'
import { Route as AppGpsRouteImport } from './routes/_app/gps'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppLostFoundRouteImport } from './routes/_app/lost-found'
import { Route as AppNearbyRouteImport } from './routes/_app/nearby'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPassportRouteImport } from './routes/_app/passport'
import { Route as AppPetsRouteImport } from './routes/_app/pets'
import { Route as AppQrRouteImport } from './routes/_app/qr'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShopRouteImport } from './routes/_app/shop'
import { Route as ScanPetIdRouteImport } from './routes/scan.$petId'
import { Route as AppPetsPetIdRouteImport } from './routes/_app/pets.$petId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFunRoute = AppFunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFutureRoute = AppFutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGpsRoute = AppGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLostFoundRoute = AppLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNearbyRoute = AppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPassportRoute = AppPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPetsRoute = AppPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRouteRoute,
} as any)
const ScanPetIdRoute = ScanPetIdRouteImport.update({
  id: '/scan/$petId',
  path: '/scan/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsPetIdRoute = AppPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => AppPetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/community': typeof AppCommunityRoute
  '/emergency': typeof AppEmergencyRoute
  '/finance': typeof AppFinanceRoute
  '/fun': typeof AppFunRoute
  '/future': typeof AppFutureRoute
  '/gps': typeof AppGpsRoute
  '/health': typeof AppHealthRoute
  '/home': typeof AppHomeRoute
  '/lost-found': typeof AppLostFoundRoute
  '/nearby': typeof AppNearbyRoute
  '/notifications': typeof AppNotificationsRoute
  '/passport': typeof AppPassportRoute
  '/pets': typeof AppPetsRouteWithChildren
  '/qr': typeof AppQrRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/scan/$petId': typeof ScanPetIdRoute
  '/pets/$petId': typeof AppPetsPetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/community': typeof AppCommunityRoute
  '/emergency': typeof AppEmergencyRoute
  '/finance': typeof AppFinanceRoute
  '/fun': typeof AppFunRoute
  '/future': typeof AppFutureRoute
  '/gps': typeof AppGpsRoute
  '/health': typeof AppHealthRoute
  '/home': typeof AppHomeRoute
  '/lost-found': typeof AppLostFoundRoute
  '/nearby': typeof AppNearbyRoute
  '/notifications': typeof AppNotificationsRoute
  '/passport': typeof AppPassportRoute
  '/pets': typeof AppPetsRouteWithChildren
  '/qr': typeof AppQrRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/scan/$petId': typeof ScanPetIdRoute
  '/pets/$petId': typeof AppPetsPetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/fun': typeof AppFunRoute
  '/_app/future': typeof AppFutureRoute
  '/_app/gps': typeof AppGpsRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/lost-found': typeof AppLostFoundRoute
  '/_app/nearby': typeof AppNearbyRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/passport': typeof AppPassportRoute
  '/_app/pets': typeof AppPetsRouteWithChildren
  '/_app/qr': typeof AppQrRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shop': typeof AppShopRoute
  '/scan/$petId': typeof ScanPetIdRoute
  '/_app/pets/$petId': typeof AppPetsPetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/community'
    | '/emergency'
    | '/finance'
    | '/fun'
    | '/future'
    | '/gps'
    | '/health'
    | '/home'
    | '/lost-found'
    | '/nearby'
    | '/notifications'
    | '/passport'
    | '/pets'
    | '/qr'
    | '/services'
    | '/settings'
    | '/shop'
    | '/scan/$petId'
    | '/pets/$petId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/community'
    | '/emergency'
    | '/finance'
    | '/fun'
    | '/future'
    | '/gps'
    | '/health'
    | '/home'
    | '/lost-found'
    | '/nearby'
    | '/notifications'
    | '/passport'
    | '/pets'
    | '/qr'
    | '/services'
    | '/settings'
    | '/shop'
    | '/scan/$petId'
    | '/pets/$petId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_app/ai'
    | '/_app/community'
    | '/_app/emergency'
    | '/_app/finance'
    | '/_app/fun'
    | '/_app/future'
    | '/_app/gps'
    | '/_app/health'
    | '/_app/home'
    | '/_app/lost-found'
    | '/_app/nearby'
    | '/_app/notifications'
    | '/_app/passport'
    | '/_app/pets'
    | '/_app/qr'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/shop'
    | '/scan/$petId'
    | '/_app/pets/$petId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ScanPetIdRoute: typeof ScanPetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fun': {
      id: '/_app/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof AppFunRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/future': {
      id: '/_app/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof AppFutureRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/gps': {
      id: '/_app/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof AppGpsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lost-found': {
      id: '/_app/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof AppLostFoundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/nearby': {
      id: '/_app/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AppNearbyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/passport': {
      id: '/_app/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AppPassportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pets': {
      id: '/_app/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AppPetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/qr': {
      id: '/_app/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/scan/$petId': {
      id: '/scan/$petId'
      path: '/scan/$petId'
      fullPath: '/scan/$petId'
      preLoaderRoute: typeof ScanPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pets/$petId': {
      id: '/_app/pets/$petId'
      path: '/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof AppPetsPetIdRouteImport
      parentRoute: typeof AppPetsRoute
    }
  }
}

interface AppPetsRouteChildren {
  AppPetsPetIdRoute: typeof AppPetsPetIdRoute
}

const AppPetsRouteChildren: AppPetsRouteChildren = {
  AppPetsPetIdRoute: AppPetsPetIdRoute,
}

const AppPetsRouteWithChildren =
  AppPetsRoute._addFileChildren(AppPetsRouteChildren)

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFunRoute: typeof AppFunRoute
  AppFutureRoute: typeof AppFutureRoute
  AppGpsRoute: typeof AppGpsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLostFoundRoute: typeof AppLostFoundRoute
  AppNearbyRoute: typeof AppNearbyRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPassportRoute: typeof AppPassportRoute
  AppPetsRoute: typeof AppPetsRouteWithChildren
  AppQrRoute: typeof AppQrRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFunRoute: AppFunRoute,
  AppFutureRoute: AppFutureRoute,
  AppGpsRoute: AppGpsRoute,
  AppHealthRoute: AppHealthRoute,
  AppHomeRoute: AppHomeRoute,
  AppLostFoundRoute: AppLostFoundRoute,
  AppNearbyRoute: AppNearbyRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPassportRoute: AppPassportRoute,
  AppPetsRoute: AppPetsRouteWithChildren,
  AppQrRoute: AppQrRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ScanPetIdRoute: ScanPetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
